apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine3.17
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432

        env:        
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password

        - name: POSTGRES_USER
          valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: user

        - name: POSTGRES_DB
          valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: user

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: LoadBalancer
  selector:
    app: postgres-deployment
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 31000